version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - app-network

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local

networks:
  app-network:
    driver: bridge

